In [2]:
import pandas as pd
import matplotlib as plt

loans_df = pd.read_csv(r"C:\Users\user\Desktop\2026\Data Analytics\Data Sets\loans\loans_full_schema.csv")
loans_df.head()

,Unnamed: 0,emp_title,emp_length,state,homeownership,annual_income,verified_income,debt_to_income,annual_income_joint,verification_income_joint,...,sub_grade,issue_month,loan_status,initial_listing_status,disbursement_method,balance,paid_total,paid_principal,paid_interest,paid_late_fees
0,1,global config engineer,3.0,NJ,MORTGAGE,90000.0,Verified,18.01,NaN,NaN,...,C3,Mar-2018,Current,whole,Cash,27015.86,1999.33,984.14,1015.19,0.0
1,2,warehouse office clerk,10.0,HI,RENT,40000.0,Not Verified,5.04,NaN,NaN,...,C1,Feb-2018,Current,whole,Cash,4651.37,499.12,348.63,150.49,0.0
2,3,assembly,3.0,WI,RENT,40000.0,Source Verified,21.15,NaN,NaN,...,D1,Feb-2018,Current,fractional,Cash,1824.63,281.80,175.37,106.43,0.0
3,4,customer service,1.0,PA,RENT,30000.0,Not Verified,10.16,NaN,NaN,...,A3,Jan-2018,Current,whole,Cash,18853.26,3312.89,2746.74,566.15,0.0
4,5,security supervisor,10.0,CA,RENT,35000.0,Verified,57.96,57000.0,Verified,...,C3,Mar-2018,Current,whole,Cash,21430.15,2324.65,1569.85,754.80,0.0

In [3]:
loans_df.columns

Index(['Unnamed: 0', 'emp_title', 'emp_length', 'state', 'homeownership',
       'annual_income', 'verified_income', 'debt_to_income',
       'annual_income_joint', 'verification_income_joint',
       'debt_to_income_joint', 'delinq_2y', 'months_since_last_delinq',
       'earliest_credit_line', 'inquiries_last_12m', 'total_credit_lines',
       'open_credit_lines', 'total_credit_limit', 'total_credit_utilized',
       'num_collections_last_12m', 'num_historical_failed_to_pay',
       'months_since_90d_late', 'current_accounts_delinq',
       'total_collection_amount_ever', 'current_installment_accounts',
       'accounts_opened_24m', 'months_since_last_credit_inquiry',
       'num_satisfactory_accounts', 'num_accounts_120d_past_due',
       'num_accounts_30d_past_due', 'num_active_debit_accounts',
       'total_debit_limit', 'num_total_cc_accounts', 'num_open_cc_accounts',
       'num_cc_carrying_balance', 'num_mort_accounts',
       'account_never_delinq_percent', 'tax_liens', 'public_record_bankrupt',
       'loan_purpose', 'application_type', 'loan_amount', 'term',
       'interest_rate', 'installment', 'grade', 'sub_grade', 'issue_month',
       'loan_status', 'initial_listing_status', 'disbursement_method',
       'balance', 'paid_total', 'paid_principal', 'paid_interest',
       'paid_late_fees'],
      dtype='object')

In [5]:
loans_df = loans_df[['emp_length','annual_income','debt_to_income','balance','paid_total','paid_principal','paid_interest','paid_late_fees','interest_rate','term','loan_amount']]

loans_df

,emp_length,annual_income,debt_to_income,balance,paid_total,paid_principal,paid_interest,paid_late_fees,interest_rate,term,loan_amount
0,3.0,90000.0,18.01,27015.86,1999.33,984.14,1015.19,0.0,14.07,60,28000
1,10.0,40000.0,5.04,4651.37,499.12,348.63,150.49,0.0,12.61,36,5000
2,3.0,40000.0,21.15,1824.63,281.80,175.37,106.43,0.0,17.09,36,2000
3,1.0,30000.0,10.16,18853.26,3312.89,2746.74,566.15,0.0,6.72,36,21600
4,10.0,35000.0,57.96,21430.15,2324.65,1569.85,754.80,0.0,14.07,36,23000
...,...,...,...,...,...,...,...,...,...,...,...
9995,10.0,108000.0,22.28,21586.34,2969.80,2413.66,556.14,0.0,7.35,36,24000
9996,8.0,121000.0,32.38,9147.44,1456.31,852.56,603.75,0.0,19.03,36,10000
9997,10.0,67000.0,45.26,27617.65,4620.80,2382.35,2238.45,0.0,23.88,36,30000
9998,1.0,80000.0,11.99,21518.12,2873.31,2481.88,391.43,0.0,5.32,36,24000
9999,3.0,66000.0,20.82,11574.83,1658.56,1225.17,433.39,0.0,10.91,36,12800

In [8]:
loans_df.isnull().any()

emp_length         True
annual_income     False
debt_to_income     True
balance           False
paid_total        False
paid_principal    False
paid_interest     False
paid_late_fees    False
interest_rate     False
term              False
loan_amount       False
dtype: bool

In [10]:
loans_df = loans_df.dropna()
loans_df.isnull().any()

emp_length        False
annual_income     False
debt_to_income    False
balance           False
paid_total        False
paid_principal    False
paid_interest     False
paid_late_fees    False
interest_rate     False
term              False
loan_amount       False
dtype: bool

In [11]:
loans_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9182 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   emp_length      9182 non-null   float64
 1   annual_income   9182 non-null   float64
 2   debt_to_income  9182 non-null   float64
 3   balance         9182 non-null   float64
 4   paid_total      9182 non-null   float64
 5   paid_principal  9182 non-null   float64
 6   paid_interest   9182 non-null   float64
 7   paid_late_fees  9182 non-null   float64
 8   interest_rate   9182 non-null   float64
 9   term            9182 non-null   int64
 10  loan_amount     9182 non-null   int64
dtypes: float64(9), int64(2)
memory usage: 860.8 KB

In [30]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

k = 95 #square of 9182 rounded to the nearest odd number

knn = KNeighborsClassifier(n_neighbors=k)
sc = StandardScaler()

x = loans_df[['emp_length','annual_income','debt_to_income','interest_rate','term']] #Other columns can be used for EDA
y = loans_df[['loan_amount']]

x_train, x_test, y_train, y_test = train_test_split(x , y, test_size = 0.25, random_state = 42)

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

knn.fit(x_train, y_train)
knn

C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=95)

In [31]:
predict_loans = knn.predict(x_test)
acc_score = accuracy_score(y_test, predict_loans)
print(acc_score)

0.11890243902439024

## Conclusion: KNN model is not a great fit, I am going to try Linear Regression

In [32]:
#Already import the other libraries
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

#Already have our x and y, we do not need a standard scaler so I'll retrain the data so it becomes unfitted and untransformed


x_train, x_test, y_train, y_test = train_test_split(x , y, test_size = 0.25, random_state = 42)

lm = LinearRegression()

lm.fit(x_train, y_train)
lm

LinearRegression()

In [33]:
predicted_loans = lm.predict(x_test)
linear_acc_score = r2_score(y_test, predicted_loans)
print(linear_acc_score)

0.25978281459325714

## Linear Model is 26% accurate, cannot be adopted and may need more training data to make better and accurate predictions